/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantprojectg6;

import edu.sit.cs.db.CSDbDelegate;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JamesP
 */
public class Order2 extends javax.swing.JFrame {

    /**
     * Creates new form Order2
     */
    public Queue1 q = new Queue1();
    int price = 0;
    String foodName;
    int foodPrice;
    int countCoke = 0, countCake = 0, countPepsi = 0, countSpa = 0, countRamen = 0, countCupcake = 0;
    CSDbDelegate db = new CSDbDelegate("cs14sitkmutt.me", "3306", "CSC105_G6", "CSC105_G6", "CSC105_G6");
    
    public Order2() {
        initComponents();
        tableLabel.setText("Table " + q.getTable().getCurrentTable());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coke = new javax.swing.JButton();
        pepsi = new javax.swing.JButton();
        cake = new javax.swing.JButton();
        cupcake = new javax.swing.JButton();
        spaghetti = new javax.swing.JButton();
        ramen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        clear = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tableLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        coke.setIcon(new javax.swing.ImageIcon("C:\\Users\\JamesP\\Documents\\NetBeansProjects\\RestaurantProjectG6\\src\\restaurantprojectg6\\coke.png")); // NOI18N
        coke.setText("Coke");
        coke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeActionPerformed(evt);
            }
        });

        pepsi.setIcon(new javax.swing.ImageIcon("C:\\Users\\JamesP\\Documents\\NetBeansProjects\\RestaurantProjectG6\\src\\restaurantprojectg6\\Pepsi.png")); // NOI18N
        pepsi.setText("pepsi");
        pepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepsiActionPerformed(evt);
            }
        });

        cake.setIcon(new javax.swing.ImageIcon("C:\\Users\\JamesP\\Documents\\NetBeansProjects\\RestaurantProjectG6\\src\\restaurantprojectg6\\cake.png")); // NOI18N
        cake.setText("cake");
        cake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cakeActionPerformed(evt);
            }
        });

        cupcake.setIcon(new javax.swing.ImageIcon("C:\\Users\\JamesP\\Documents\\NetBeansProjects\\RestaurantProjectG6\\src\\restaurantprojectg6\\cupcake.png")); // NOI18N
        cupcake.setText("cupcake");
        cupcake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupcakeActionPerformed(evt);
            }
        });

        spaghetti.setIcon(new javax.swing.ImageIcon("C:\\Users\\JamesP\\Documents\\NetBeansProjects\\RestaurantProjectG6\\src\\restaurantprojectg6\\pasta.png")); // NOI18N
        spaghetti.setText(" Spaghetti");
        spaghetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaghettiActionPerformed(evt);
            }
        });

        ramen.setIcon(new javax.swing.ImageIcon("C:\\Users\\JamesP\\Documents\\NetBeansProjects\\RestaurantProjectG6\\src\\restaurantprojectg6\\Ramen.png")); // NOI18N
        ramen.setText("Ramen");
        ramen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramenActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        priceLabel.setText("Total price: ");

        back.setText("Back");

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("TH Charm of AU", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Order");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tableLabel.setText("Table: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(doneButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(coke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ramen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pepsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spaghetti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cupcake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(tableLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(priceLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(priceLabel)
                        .addGap(18, 18, 18)
                        .addComponent(clear))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableLabel)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pepsi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coke, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cupcake)
                            .addComponent(cake, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ramen, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spaghetti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(doneButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeActionPerformed
        foodName = "Coke";
        foodPrice = 15;
        
        Object[] row = { foodName, foodPrice };

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addRow(row);
        price += foodPrice;
        countCoke++;
        priceLabel.setText("Total price: " + price);
    }//GEN-LAST:event_cokeActionPerformed

    private void pepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepsiActionPerformed
        foodName = "Pepsi";
        foodPrice = 15;
        
        Object[] row = { foodName, foodPrice };

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addRow(row);
        price += foodPrice;
        countPepsi++;
        priceLabel.setText("Total price: " + price);
    }//GEN-LAST:event_pepsiActionPerformed

    private void cupcakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupcakeActionPerformed
        foodName = "Cupcake";
        foodPrice = 40;
        
        Object[] row = { foodName, foodPrice };

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addRow(row);
        price += foodPrice;
        countCupcake++;
        priceLabel.setText("Total price: " + price);
    }//GEN-LAST:event_cupcakeActionPerformed

    private void cakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cakeActionPerformed
        foodName = "Cake";
        foodPrice = 70;
        
        Object[] row = { foodName, foodPrice };

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addRow(row);
        price += foodPrice;
        countCake++;
        priceLabel.setText("Total price: " + price);
    }//GEN-LAST:event_cakeActionPerformed

    private void spaghettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaghettiActionPerformed
        foodName = "Spaghetti";
        foodPrice = 120;
        
        Object[] row = { foodName, foodPrice };

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addRow(row);
        price += foodPrice;
        countSpa++;
        priceLabel.setText("Total price: " + price);
    }//GEN-LAST:event_spaghettiActionPerformed

    private void ramenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramenActionPerformed
        foodName = "Ramen";
        foodPrice = 100;
        
        Object[] row = { foodName, foodPrice };

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addRow(row);
        price += foodPrice;
        countRamen++;
        priceLabel.setText("Total price: " + price);
    }//GEN-LAST:event_ramenActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        countCoke = 0; countCake = 0; countPepsi = 0; countSpa = 0; countRamen = 0; countCupcake = 0; price = 0;
        priceLabel.setText("Total price: " + price);
    }//GEN-LAST:event_clearActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        System.out.println(db.connect());
        String getCoke = "SELECT count FROM RESTAURANT_Food WHERE RESTAURANT_Food.foodName = 'Coke' ";
        HashMap cCount = db.queryRow(getCoke);
        int cokeCount = Integer.parseInt((String)(cCount.get("count")));
        
        String updateCoke = "UPDATE RESTAURANT_Food SET count = '" + (cokeCount+countCoke) + "' WHERE RESTAURANT_Food.foodName = 'Coke' ";
        db.executeQuery(updateCoke);
        
        String getCake = "SELECT count FROM RESTAURANT_Food WHERE RESTAURANT_Food.foodName = 'Cake' ";
        HashMap caCount = db.queryRow(getCake);
        int cakeCount = Integer.parseInt((String)(caCount.get("count")));
        
        String updateCake = "UPDATE RESTAURANT_Food SET count = '" + (cakeCount+countCake) + "' WHERE RESTAURANT_Food.foodName = 'Cake' ";
        db.executeQuery(updateCake);
        
        String getCup = "SELECT count FROM RESTAURANT_Food WHERE RESTAURANT_Food.foodName = 'Cupcake' ";
        HashMap cuCount = db.queryRow(getCup);
        int cupCount = Integer.parseInt((String)(cuCount.get("count")));
        
        String updateCup = "UPDATE RESTAURANT_Food SET count = '" + (cupCount+countCupcake) + "' WHERE RESTAURANT_Food.foodName = 'Cupcake' ";
        db.executeQuery(updateCup);
        
        String getPepsi = "SELECT count FROM RESTAURANT_Food WHERE RESTAURANT_Food.foodName = 'Pepsi' ";
        HashMap pCount = db.queryRow(getPepsi);
        int pepsiCount = Integer.parseInt((String)(pCount.get("count")));
        
        String updatePepsi = "UPDATE RESTAURANT_Food SET count = '" + (pepsiCount+countPepsi) + "' WHERE RESTAURANT_Food.foodName = 'Pepsi' ";
        db.executeQuery(updatePepsi);
        
        String getRamen = "SELECT count FROM RESTAURANT_Food WHERE RESTAURANT_Food.foodName = 'Ramen' ";
        HashMap rCount = db.queryRow(getRamen);
        int ramenCount = Integer.parseInt((String)(rCount.get("count")));
        
        String updateRamen = "UPDATE RESTAURANT_Food SET count = '" + (ramenCount+countRamen) + "' WHERE RESTAURANT_Food.foodName = 'Ramen' ";
        db.executeQuery(updateRamen);
        
        String getSpa = "SELECT count FROM RESTAURANT_Food WHERE RESTAURANT_Food.foodName = 'Spaghetti' ";
        HashMap sCount = db.queryRow(getSpa);
        int spaCount = Integer.parseInt((String)(sCount.get("count")));
        
        String updateSpa = "UPDATE RESTAURANT_Food SET count = '" + (spaCount+countSpa) + "' WHERE RESTAURANT_Food.foodName = 'Spaghetti' ";
        db.executeQuery(updateSpa);
        
        String updatePrice = "UPDATE RESTAURANT_Table SET cost = " + price + " WHERE RESTAURANT_Table.No = " + q.getTable().getCurrentTable();
        db.executeQuery(updatePrice);
        System.out.println(db.disconnect());
        dispose();
        new Function1().setVisible(true);
    }//GEN-LAST:event_doneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton cake;
    private javax.swing.JButton clear;
    private javax.swing.JButton coke;
    private javax.swing.JButton cupcake;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pepsi;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton ramen;
    private javax.swing.JButton spaghetti;
    private javax.swing.JLabel tableLabel;
    // End of variables declaration//GEN-END:variables
}
